### ISSUE TITLE
Qb-Traphouse Use

### ISSUE THREAD

**Issue by Exizt11** [qbcore-framework/qb-traphouse#26]
Hello. I've used txAdmin to download your files via the txadmin file you provide. I have not changed anything anywhere. Pure default files. I am at the coordinates for the traphouse and there is no enter on the door. I've done 3 recipe reinstalls and cannot figure it out. In previous attempts, I've tried setting opened = true and changing the location. I also notice this with another modified version of the file I tried before. In case it was a factor, I've tried on and off police role.

What am I doing wrong and how do I get this working?

Cheers

**Comment by erikmeyer08** [comment]
I'm having the same issue..

**Comment by Exizt11** [comment]
I just figured it out after digging in the Qbcore discord threads. Use /entertraphouse

**Comment by Hustle43** [comment]
> Hello. I've used txAdmin to download your files via the txadmin file you provide. I have not changed anything anywhere. Pure default files. I am at the coordinates for the traphouse and there is no enter on the door. I've done 3 recipe reinstalls and cannot figure it out. In previous attempts, I've tried setting opened = true and changing the location. I also notice this with another modified version of the file I tried before. In case it was a factor, I've tried on and off police role.
> 
> What am I doing wrong and how do I get this working?
> 
> Cheers

i cant even find the traphouse, My coordinates isnt working properly or im reading it wrong help?
