### ISSUE TITLE
Nil value (global 'Lang')

### ISSUE THREAD

**Issue by GhostLegionRP** [qbcore-framework/qb-traphouse#30]
[    c-scripting-core] Creating script environments for qb-traphouse
[ script:qb-traphouse] Error loading script server/main.lua in resource qb-traphouse: @qb-traphouse/server/main.lua:222: attempt to index a nil value (global 'Lang')
[ script:qb-traphouse] stack traceback:
[ script:qb-traphouse] 	@qb-traphouse/server/main.lua:222: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[ citizen-server-impl] Started resource qb-traphouse

**Comment by W0lv3sxD** [comment]
Hey, I have the exact same problem. Hoping for a quick answer/fix.

Thank you.

**Comment by SrPeterr** [comment]
Found a temp solution
Change
```
if GetConvar('qb_locale', 'en') == 'en' then
    Lang = Locale:new({
        phrases = Translations,
        warnOnMissing = true
    })    
end
```
To this
```
Lang = Locale:new({
    phrases = Translations,
    warnOnMissing = true
})
```

Or you can set on your `server.cfg` a `setr qb_locale "en"` I think

**Comment by istesoruisteboru** [comment]
if you want to create new language file like

esp.lua
first you need to create esp.lua make your own translation then
find this row.
```
if GetConvar('qb_locale', 'en') == 'en' then
    Lang = Locale:new({
        phrases = Translations,
        warnOnMissing = true
    })    
end
```

change it to
```

if GetConvar('qb_locale', 'esp') == 'esp' then
    Lang = Locale:new({
        phrases = Translations,
        warnOnMissing = true
    })    
end
```

if your server cfg has `setr qb_locale "esp"` it works well.
