### ISSUE TITLE
[BUG] Cleaning Money

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-traphouse#37]
Receiving he server side exception shown below when trying to clean money in the trap house.

![image](https://user-images.githubusercontent.com/43043270/179053700-45b72a30-4354-4765-9439-9452140e23e2.png)

**Comment by tom-osborne** [comment]
@erikmeyer08 Looks like your markedbills item has no metadata against it. How are you obtaining the markedbills?
