### ISSUE TITLE
[BUG] Traphouse inventory no mouse control?

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-traphouse#42]
**Describe the bug**
Opening the traphouse inventory gives no mouse control

**To Reproduce**
1. Go into trap house
2. Take it over
3. 3rd/E onto the inventory location
4. Inventory comes up but mouse control still with player

**Expected behavior**
Mouse control on inventory so you can move items etc

**Screenshots**
Video: https://youtu.be/zNCfTculOWg

**Questions (please complete the following information):**
 - When you last updated: Complete fresh qb-script pull (double checked core/inventory and traphouse also to be 100%
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by nzkfc** [comment]
Just to add, I re-downloaded a fresh qb server locally and re-tested, same issue.

**Comment by Broculos** [comment]
> Just to add, I re-downloaded a fresh qb server locally and re-tested, same issue.

Did you manage to solve this problem?

**Comment by nzkfc** [comment]
No unfortunately

**Comment by nzkfc** [comment]
Anyone else having this issue? It seems odd that two people have this but no one else has it, like are people updating and not running through their scripts to test the update works...

**Comment by DalKoe** [comment]
im having this issue also, fresh scripts

**Comment by nzkfc** [comment]
@tom-osborne sorry for the tag, but this is another one that we have been unable to use the whole script since before 17th Sept.

**Comment by tom-osborne** [comment]
@nzkfc Fixed in #45 - Can you confirm this works for you too?
