### ISSUE TITLE
Big ERROR when putting items in 

### ISSUE THREAD

**Issue by trillindadon** [qbcore-framework/qb-traphouse#6]
[ script:qb-traphouse] SCRIPT ERROR: @qb-traphouse/server/main.lua:177: attempt to perform arithmetic on a nil value (field 'worth')
[ script:qb-traphouse] SCRIPT ERROR: @qb-traphouse/server/main.lua:177: attempt to perform arithmetic on a nil value (field 'worth')
[ script:qb-traphouse] SCRIPT ERROR: @qb-traphouse/server/main.lua:177: attempt to perform arithmetic on a nil value (field 'worth')

**Comment by ihyajb** [comment]
could not replicate. I suggest making sure everything is up to date.
